language: c
compiler: gcc

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y check 
script: 
    - autoreconf -iv
    - ./configure
    - make && make check

notification:
    email:
        - for.teketel@gmail.com
